#!/usr/bin/env bash

APP="short_url"

# 自动以 git revision 作为发布名称
AUTO_VERSION="revision"

BUILD_HOST="url"
BUILD_USER="Youthink"
BUILD_AT="/tmp/edeliver/short_url/builds"

PRODUCTION_HOSTS="url" # deploy / production hosts separated by space
PRODUCTION_USER="Youthink" # local user at deploy hosts

DELIVER_TO="/home/web/" # deploy directory on production hosts

HEX_MIRROR_URL="https://hexpm.upyun.com"

# For *Phoenix* projects, symlink prod.secret.exs to our tmp source
pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/home/builder/short_url.prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
    "
  fi
}

